channels:
- conda-forge
dependencies:
- python=3.9.21
- pip<=25.0
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - numpy==1.24.3
  - pandas==2.2.3
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
